version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  send:
    build:
      context: ./send
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

  receive:
    build:
      context: ./receive
    depends_on:
      - rabbitmq
    ports:
      - "3001:3001"
