version: '3.8'

services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user # Esto deberia ser una variable de entorno
      RABBITMQ_DEFAULT_PASS: password # Esto deberia ser una variable de entorno

  send:
    build:
      context: ./send
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

  receive:
    build:
      context: ./receive
    depends_on:
      - rabbitmq
    ports:
      - "3001:3001"
