version: '3.8'

services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user # Esto deberia ser una variable de entorno
      RABBITMQ_DEFAULT_PASS: password # Esto deberia ser una variable de entorno

  send:
    build:
      context: ./send
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

  receive1:
    build:
      context: ./receive1
    depends_on:
      - rabbitmq
    ports:
      - "3001:3001"
    
  receive4:
    build:
      context: ./receive4
    depends_on:
      - rabbitmq
    ports:
      - "3004:3004"

  receive2:
    build:
      context: ./receive2
    depends_on:
      - rabbitmq
    ports:
      - "3002:3002"

  receive3:
    build:
      context: ./receive3
    depends_on:
      - rabbitmq
    ports:
      - "3003:3003"